using System.Globalization;

namespace LightHub.Desktop;

public sealed class Strings
{
    public bool Chinese { get; }
    public Strings(bool? chinese = null) => Chinese = chinese ?? CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "zh";
    public string this[string key] => Values.TryGetValue(key, out var pair) ? pair[Chinese ? 1 : 0] : key;
    private static readonly Dictionary<string, string[]> Values = new()
    {
        ["Devices"] = ["Devices", "设备"],
        ["Scan"] = ["Refresh devices", "刷新设备"],
        ["Cancel"] = ["Cancel", "取消"],
        ["Profile"] = ["Onboard profiles", "板载配置"],
        ["Backups"] = ["Backups & recovery", "备份与恢复"],
        ["BackupSummary"] = ["{0} backups · {1:F1} KB · {2} protected", "{0} 份备份 · {1:F1} KB · {2} 份受保护"],
        ["UnknownBackup"] = ["Unknown device", "未知设备"],
        ["ProtectedBackup"] = ["Recovery protected", "恢复保护"],
        ["VerifiedBackup"] = ["Checksum verified", "校验通过"],
        ["InvalidBackup"] = ["Unreadable backup", "备份无法读取"],
        ["BackupUnavailable"] = ["Backup management unavailable.", "备份管理暂不可用。"],
        ["DeleteBackups"] = ["Delete selected", "删除选中备份"],
        ["CleanupBackups"] = ["Clean up old backups…", "清理旧备份…"],
        ["ExportSelectedBackup"] = ["Export selected", "导出选中备份"],
        ["RestoreSelectedBackup"] = ["Restore selected", "恢复选中备份"],
        ["RefreshBackups"] = ["Refresh backups", "刷新备份"],
        ["DiagnosticDetails"] = ["Diagnostic details", "诊断详情"],
        ["DeleteBackupsQuestion"] = ["Move these {0} backups to the local recycle area?", "将这 {0} 份备份移入本地回收区？"],
        ["CleanupBackupsQuestion"] = ["Keep the newest 10 automatic backups per device and all protected backups. Move these {0} older backups to the recycle area?", "每台设备保留最近 10 份自动备份和所有受保护备份。将以下 {0} 份旧备份移入回收区？"],
        ["NoCleanup"] = ["No old backups to clean up.", "没有可清理的旧备份。"],
        ["BackupsDeleted"] = ["Deleted {0} local backups.", "已删除 {0} 份本地备份。"],
        ["Support"] = ["Compatibility", "兼容性"],
        ["Dpi"] = ["DPI stages", "DPI 档位"],
        ["CurrentDpi"] = ["Current DPI (temporary)", "当前 DPI（临时）"],
        ["SetCurrentDpi"] = ["Try DPI", "试用 DPI"],
        ["EndPreview"] = ["End preview", "结束试用"],
        ["PreviewEnded"] = ["Preview ended; starting DPI restored.", "试用结束，起始 DPI 已恢复。"],
        ["PreviewUnknown"] = ["Preview ownership changed; DPI was not restored. Read device state.", "试用状态已变化，未恢复 DPI。请重新读取设备。"],
        ["ReplacementStage"] = ["Replacement for removed current stage (optional)", "删除当前档位后的替代档位（可选）"],
        ["ReplacementStageRequired"] = ["Choose an enabled replacement for the current DPI stage.", "请选择一个有效档位替代被删除的当前 DPI 档位。"],
        ["ActivateQuestion"] = ["Activate the selected saved onboard slot? Unsaved edits are not written.", "启用选中的已保存板载槽？此操作不会保存草稿。"],
        ["SaveDraft"] = ["Keep local draft", "保留本地草稿"],
        ["DraftNotSaved"] = ["Local draft could not be saved; keep this window open.", "本地草稿暂存失败，请保留当前窗口。"],
        ["NameBackup"] = ["Backup properties", "备份属性"],
        ["Milestone"] = ["Protected milestone", "保护为里程碑"],
        ["RenamePreset"] = ["Rename selected", "重命名选中预设"],
        ["Presets"] = ["Presets", "本地预设"],
        ["PresetName"] = ["Preset name", "预设名称"],
        ["NewPreset"] = ["New preset", "新预设"],
        ["SavePreset"] = ["Save a new preset", "另存为新预设"],
        ["LoadPreset"] = ["Load into draft", "载入为草稿"],
        ["DeletePreset"] = ["Remove preset", "移除预设"],
        ["DeletePresetQuestion"] = ["Remove this local preset?", "移除此本地预设？"],
        ["ImportPreset"] = ["Import preset", "导入预设"],
        ["ExportPreset"] = ["Export preset", "导出预设"],
        ["RecoverDraft"] = ["Recover local draft", "恢复本地草稿"],
        ["PinBackup"] = ["Toggle pin", "切换置顶保护"],
        ["Trash"] = ["Recycle area", "回收区"],
        ["RecoverTrash"] = ["Recover file", "找回文件"],
        ["EraseTrash"] = ["Delete permanently", "永久删除"],
        ["EraseQuestion"] = ["Permanently delete this backup? This cannot be undone.", "永久删除此备份？此操作无法撤销。"],
        ["CurrentDpiApplied"] = ["Current DPI verified; onboard profile unchanged.", "当前 DPI 已验证，板载配置未更改。"],
        ["Default"] = ["Default stage", "默认档位"],
        ["Shift"] = ["DPI Shift", "DPI Shift"],
        ["Rate"] = ["Polling rate", "回报率"],
        ["Buttons"] = ["Button assignments", "按键映射"],
        ["Activate"] = ["Make active in onboard mode", "设为当前板载配置"],
        ["Apply"] = ["Save to selected slot", "保存到选中槽位"],
        ["Undo"] = ["Discard changes", "撤销更改"],
        ["Read"] = ["Read device", "读取设备"],
        ["Export"] = ["Export backup", "导出备份"],
        ["Restore"] = ["Restore backup…", "恢复备份…"],
        ["Diagnostics"] = ["Export diagnostics", "导出诊断"],
        ["Ready"] = ["Ready", "准备就绪"],
        ["Reading"] = ["Reading device memory…", "正在读取设备内存…"],
        ["Scanning"] = ["Discovering HID++ devices…", "正在发现 HID++ 设备…"],
        ["NoDevice"] = ["No available device", "没有可用设备"],
        ["Select"] = ["Select a device", "选择设备"],
        ["Dirty"] = ["Unsaved changes", "有未保存的更改"],
        ["Saved"] = ["Verified. You can close LightHub.", "已通过回读验证，可以退出 LightHub。"],
        ["Confirm"] = ["Confirm", "确认"],
        ["DiscardQuestion"] = ["Discard unsaved changes?", "放弃尚未写入的更改？"],
        ["WriteQuestion"] = ["Write the following changes? An automatic backup will be saved first.", "写入以下更改？操作前会自动保存备份。"],
        ["RestoreQuestion"] = ["Restore this backup to the same physical device?", "将此备份恢复到同一物理设备？"],
        ["ReadOnly"] = ["Read-only", "只读"],
        ["Writable"] = ["Onboard write driver", "板载写入驱动"],
        ["None"] = ["None", "无"],
        ["Enabled"] = ["Enabled", "已启用"],
        ["Disabled"] = ["Disabled", "已禁用"],
        ["Stage"] = ["Stage", "档位"],
        ["Button"] = ["Button", "按键"],
        ["LeftButton"] = ["Left main button", "左主键"],
        ["RightButton"] = ["Right main button", "右主键"],
        ["WheelButton"] = ["Wheel click", "滚轮按下"],
        ["LeftRear"] = ["Left rear side", "左侧后键"],
        ["LeftFront"] = ["Left front side", "左侧前键"],
        ["BottomDpi"] = ["Underside DPI", "底部 DPI 键"],
        ["RightRear"] = ["Right rear side", "右侧后键"],
        ["RightFront"] = ["Right front side", "右侧前键"],
        ["TopView"] = ["Top view", "俯视图"],
        ["Checking for conflicts"] = ["Checking for conflicts", "正在检查配置冲突"],
        ["Verifying device memory"] = ["Verifying device memory", "正在回读验证设备内存"],
        ["Pending"] = ["An interrupted write needs review. Open Backups & recovery.", "存在未完成的写入，请检查备份与恢复。"],
        ["Demo"] = ["Demo · hardware writes disabled", "演示模式 · 硬件写入已禁用"],
        ["Error"] = ["Operation failed", "操作失败"],
        ["About"] = ["About", "关于"],
        ["Custom"] = ["Keyboard combination", "键盘组合键"],
        ["Copy"] = ["Copy", "复制"],
        ["NoChanges"] = ["No changes to write", "没有需要写入的更改"],
        ["Busy"] = ["Device operation in progress", "设备操作进行中"],
        ["Reconnected"] = ["Device state refreshed", "设备状态已刷新"],
        ["Onboard"] = ["Onboard mode", "板载模式"],
        ["Host"] = ["Host mode", "软件控制模式"]
    };
}
